# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitternow', '0012_auto_20161218_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealconsumption',
            old_name='consumption_id',
            new_name='consumptionhistory',
        ),
        migrations.RenameField(
            model_name='mealconsumption',
            old_name='meal_id',
            new_name='meal',
        ),
    ]
